import Head from 'next/head';
import Link from 'next/link';
import {gql, useQuery} from '@apollo/client'

const AllRentsQuery = gql`
  query {
    rentLogs {
      id
      name
      rentalType
      rentalSize
      address
      year
      rent
    }
  }
`

function formatSize (rentalSize) {
  switch (rentalSize) {
    case 'TWOANDAHALF':
      return '2 1/2 (Studio)';
    case 'THREEANDAHALF':
      return '3 1/2 (One bedroom)';
    case 'FOURANDAHALF':
      return '4 1/2 (Two bedrooms)';
      case 'FIVEANDAHALF':
        return '5 1/2 (Three bedrooms)';
  }
}

export default function RentPage() {

  const {data, loading, error} = useQuery(AllRentsQuery)
  console.log(data)

  if (loading) return <p>Loading...</p>
  if (error) return <p>Oh no.... {error.message}</p>

  const formatFeedbackType = (feedback) => {
    switch (feedback) {
      case 'APARTMENT':
        return 'bg-green-500 text-green-800';
      case 'HOUSE':
        return 'bg-yellow-300 text-yellow-800';
      case 'DUPLEX':
        return 'bg-red-400 text-red-800';
    }
  };


  return (
    <div>
      <Head>
        <title>Historical Rent Database</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="my- my-36 h-auto">
        <div className="container mx-auto max-w-screen-lg px-4">
          <h1 className="text-3xl mb-5 font-bold tracking-wide text-white">
            Rent Logs
          </h1>
          <section className="flex flex-col  ">
            <div className="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
              <div className="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                <div className="shadow overflow-hidden border-b border-gray-800 rounded-lg">
                  <table className="min-w-full divide-y divide-gray-800 ">
                    <thead className="bg-gray-800">
                      <tr>
                        <th
                          scope="col"
                          className="px-6 py-3 text-left text-xs font-medium text-gray-300 uppercase tracking-wider"
                        >
                          Name
                        </th>
                        <th
                          scope="col"
                          className="px-6 py-3 text-left text-xs font-medium text-gray-300 uppercase tracking-wider"
                        >
                          Rent
                        </th>
                        <th
                          scope="col"
                          className="px-6 py-3 text-left text-xs font-medium text-gray-300 uppercase tracking-wider"
                        >
                          Address
                        </th>
                        <th
                          scope="col"
                          className="px-6 py-3 text-left text-xs font-medium text-gray-300 uppercase tracking-wider"
                        >
                          Rental Size
                        </th>
                        <th
                          scope="col"
                          className="px-6 py-3 text-left text-xs font-medium text-gray-300 uppercase tracking-wider"
                        >
                          Rental Type
                        </th>
                      </tr>
                    </thead>
                    
                <tbody className="bg-gray-700 divide-y divide-gray-500">
                                    {data.rentLogs.map((item) => (
                                      <tr key={item.id}>
                                        <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-white">
                                          {item.name}
                                        </td>
                                        <td className="px-6 py-4 whitespace-nowrap text-sm text-white">
                                          <span>{item.rent}$</span>
                                        </td>
                                        <td className="px-6 py-4 whitespace-nowrap text-sm text-white">
                                          <span>{item.address}</span>
                                        </td>
                                        <td className="px-6 py-4 whitespace-nowrap text-sm text-white">
                                          <span>{formatSize(item.rentalSize)}</span>
                                        </td>
                                        <td className="px-6 py-4 whitespace-nowrap text-sm text-white">
                                          <span>                                          
                                            {item.rentalType.toLowerCase()}
                                          </span>
                                        </td>
                                      </tr>
                                    ))}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </section>
        </div>
      </main>
    </div>
  );
}
